# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66iles.proto\"\x12\n\x10ListFilesRequest\")\n\x11ListFilesResponse\x12\x14\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x05.File\"#\n\x12SearchFilesRequest\x12\r\n\x05query\x18\x01 \x01(\t\"+\n\x13SearchFilesResponse\x12\x14\n\x05\x66iles\x18\x01 \x01(\x0b\x32\x05.File\"&\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\x0c\x32|\n\x05\x46iles\x12\x37\n\x0cGetFilesList\x12\x11.ListFilesRequest\x1a\x12.ListFilesResponse\"\x00\x12:\n\x0bSearchFiles\x12\x13.SearchFilesRequest\x1a\x14.SearchFilesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'files_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LISTFILESREQUEST']._serialized_start=15
  _globals['_LISTFILESREQUEST']._serialized_end=33
  _globals['_LISTFILESRESPONSE']._serialized_start=35
  _globals['_LISTFILESRESPONSE']._serialized_end=76
  _globals['_SEARCHFILESREQUEST']._serialized_start=78
  _globals['_SEARCHFILESREQUEST']._serialized_end=113
  _globals['_SEARCHFILESRESPONSE']._serialized_start=115
  _globals['_SEARCHFILESRESPONSE']._serialized_end=158
  _globals['_FILE']._serialized_start=160
  _globals['_FILE']._serialized_end=198
  _globals['_FILES']._serialized_start=200
  _globals['_FILES']._serialized_end=324
# @@protoc_insertion_point(module_scope)
