apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: RETO4
        - name: MYSQL_DATABASE
          value: DATABASE
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service  # Nombre del servicio
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306  # Puerto que expondrá el servicio
      targetPort: 3306
